### ISSUE TITLE
Further development & migrate to .net core

### ISSUE THREAD

**Issue by VladimirRybalko** [adamkrogh/goodreads-dotnet#1]
Dear @adamkrogh 
Seems that you don't have time for further development. Unfortunatelly many API methods is not covered yet. The last commit was about one year ago.
I think your project is a very interesting. I'm considering some .net goodreads SDKs and assume that your project is the best. I'm going to implement some missing API methods and migrate library to .NET Core or .NET Standard.
What do you think about some pull requests from me? Could I ask you to add me as a project collaborator. It will facilitate my work.

Thanks in advance.
Regards

**Comment by adamkrogh** [comment]
Hi!

You're right, I haven't worked on this library in a while, pretty crazy that it's been almost a year already! At the time, I had finished all the API methods that I was using in my side project and sopped after that. I'd love to get more methods completed and eventually publish a version 1.0. What API methods are you in need of right away?

Migrating the library to .NET Core or .NET Standard sounds like a great idea too as it seems like this is where everything is headed. I'm not too familiar with what would be involved in the migration though. The only dependency at the moment is RestSharp so hopefully it won't be too hard to migrate. Do you know what would be involved in the migration?

Do you want to start with some small pull requests for new API methods to get a feel for everything? If it all goes well I can grant you collaborator access in a bit.

Hopefully we can work together and get this library a little more feature complete. Let me know what you think. Thanks!

**Comment by VladimirRybalko** [comment]
Hi.
First of all I need all API methods for shelves. I think it will be my first PR. Ideally I try to add as many methods as I can. 1.0 version will be a good event for this project. 

I've checked ability for migration to .NET Core. Seems we need to replace RestSharp dependency to RestSharp.Net Core nuget package. It will be the first major step. May be we need to update the test engine too. But I'm not sure. It's only my ideas.

I don't mind about small pull requests. You are right, I need some time to get a feel for project.
Let's work together. I hope we get 1.0 release of this library. I'm going to add new methods soon.
Thank you.

**Comment by VladimirRybalko** [comment]
Hi @adamkrogh 
Unfortunately, I was busy for a long time. However I'm going to contribute more intensively now.
I've already added the first PR. I think I will add support for each new method as a separate PR.
Regards.

**Comment by adamkrogh** [comment]
No problem, I'm pretty busy at the moment too. Your pull request looked great, thanks! I've invited you as a collaborator to the repo if you want to skip the pull request process and push directly to the repo. Hopefully it will make it a bit easier to complete some more API methods on your end. Thanks again!

**Comment by VladimirRybalko** [comment]
Thank you so much.
