### ISSUE TITLE
Update AppVeyor config to use VS2017 and .NET Standard 2.0

### ISSUE THREAD

**Issue by VladimirRybalko** [adamkrogh/goodreads-dotnet#11]
AppVeyor CI is broken now. 
We need to update a AppVeyor config file to support a new project infrastructure.

**Comment by VladimirRybalko** [comment]
Hi @adamkrogh 
Seems AppVeyor is still not working. Could you have a look at this please?

**Comment by adamkrogh** [comment]
Sorry about that, I wanted to get the auto-generated version numbers and nuget deployments working the same way I had them in the old project type but I think it's going to take some more work.

The build is getting a little further along now but has some compile and test errors. I still don't have VS2017 set up on my machine, could you take a look at the errors here:

https://ci.appveyor.com/project/adamkrogh/goodreads-dotnet/build/0.3.1-beta-65

Thanks!

**Comment by VladimirRybalko** [comment]
Adam. 
I'll check and fix all errors.

**Comment by VladimirRybalko** [comment]
@adamkrogh 
Seems that a goodreads review with number 1700227480 does not exist anymore.
I need any other reviewId for **test** user to fix it.
Could you provide me with it please?

**Comment by adamkrogh** [comment]
I've created another review with Id 2175139156 on the test user's account. I've also sent you an email with the test credentials in case you need to create anything else.

**Comment by VladimirRybalko** [comment]
I've fixed broken unit tests. The build is green now.
I suppose we can create a new nuget package after testing new auth methods.
