### ISSUE TITLE
Genre

### ISSUE THREAD

**Issue by iamyoshita** [adamkrogh/goodreads-dotnet#16]
The Search function can just search based on given 'id' , 'title' and 'all'. But in order to search based on genre ,
The Code:
**_[QueryParameterValue("genre")]
        Genre_**
must be added to **Goodreads/Models/Request/BookSearchField.cs**

I tried it and it works perfectly fine

**Comment by VladimirRybalko** [comment]
It sounds great, would you like to prepare a PR?

**Comment by iamyoshita** [comment]
Yes!

**Comment by VladimirRybalko** [comment]
Thank you @iamyoshita .
Don't worry about it. I don't think that your small PR could cause it.
I'll check our test infrastructure and merge your pull request soon.
