### ISSUE TITLE
An item with the same key has already been added- Error

### ISSUE THREAD

**Issue by xFahim** [adamkrogh/goodreads-dotnet#19]
I was using the library for one of my projects and encountered this error out of nowhere. All I was doing, calling the client.Books.GetByBookId() method. I've already checked the parameter (BookID=929) and it's a valid one for sure. Furthermore, I've also encountered the same error while using client.Books.GetByTitle() method. 
It would be great if you could have a look at the issue. 
![image](https://user-images.githubusercontent.com/35301902/53035016-afc65a80-349e-11e9-9b2a-3ac173d7fd3c.png)

**Comment by VladimirRybalko** [comment]
@xFahim 
As I see, you tried to use our library to craw the Goodreads library. I have to note, it's strictly prohibited by developer API license.
