### ISSUE TITLE
Goodreads Create Api key + Secret

### ISSUE THREAD

**Issue by ahmeetarif** [adamkrogh/goodreads-dotnet#24]
I registered to goodreads api but there is no link for https://www.goodreads.com/api/keys, how can I create an API Key ?

**Comment by VladimirRybalko** [comment]
Hi @ahmeetarif .
Unfortunately, as of December 8th 2020, Goodreads no longer issues new developer keys for the public developer API and, moreover, they plan to retire the current version of these tools. You can find more information [here](https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs).
