### ISSUE TITLE
Issue with "Confirm or decline a friend recommendation" endpoint.

### ISSUE THREAD

**Issue by VladimirRybalko** [adamkrogh/goodreads-dotnet#3]
Seems that Goodreads endpoint is not working as describe in an official documentation.
Moreover I think method is not working at all.
There is not an ability to approve a recommendation in a web version. An user need to add a book to his shelf instead. Also I can't ignore a recommendation using the Goodreads API. Server returns the "**Not found**" response for all my requests.
I'm going to send a bug ticket to the Goodreads support. 
Will wait any feedback.

**Comment by adamkrogh** [comment]
Yeah I figured there would be a few endpoints that are incorrect or completely wrong on their end. If there is no workaround, we'll just have to make a note of that in the readme. Not much else we can do. Hopefully they get back to you on your bug ticket but I'm not too optimistic...

**Comment by VladimirRybalko** [comment]
Copy all information to the one Goodreads API issue. #9
