### ISSUE TITLE
Issue with "Destroy review" endpoint

### ISSUE THREAD

**Issue by VladimirRybalko** [adamkrogh/goodreads-dotnet#4]
@adamkrogh, you notes that "Destroy review" endpoint returns strange errors and never works.
I have investigated this and could say that the Goodreads API documentation is wrong.

The strange error said that server can't parse book identifier in request. It's really strange because I do not need to send any book id. I have looked at the web version and found that we need to send a book id instead of a reviewId. I try to do it. Unfortunately, now I'am getting Unathorized error. Moreover I've played with different combinations of parameters, values and request method. Nothing works! It's a sad.
Do you get any feedback from the Goodreads support?

**Comment by adamkrogh** [comment]
That sounds exactly like the errors I was getting too. I never filed any bug ticket with Goodreads though. If you want, you could log this issue with them and see if we get a response back. I'm thinking this issue and issue #3 will just have to be documented as broken in the Goodreads API, but hopefully we can get them to fix it. Or at least update their documentation.

Thanks for looking into this!

**Comment by VladimirRybalko** [comment]
Copy all known info to #9
