### ISSUE TITLE
Connection.ExecuteRaw() Hanging...

### ISSUE THREAD

**Issue by hfloyd** [adamkrogh/goodreads-dotnet#6]
So, I am doing a call to Client.Series.GetListByAuthorId(author.Id) but it seems to just hang. When stepping through the code, I see that the request is constructed correctly, and the response includes expected XML data from Goodreads: 

**RestSharpExtensions.ThrowIfException**
```
...
// Try and find an error from the Goodreads response
            string error = null;
            try
            {
                var document = XDocument.Parse(response.Content); <-- response.Content has expected data
...
```
The code gets to the end of "ThrowInfException" and returns the response without any exceptions.

But when it should just pass back the response data, it seems to get stuck at the very end of "Connection.ExecuteRaw()", and by stuck I mean it never gets beyond it. I have let it continue to run for 3-5 minutes before stopping the running code.

I'm not well versed in asynchronous methods... otherwise I'd try to fix this myself. I'm just not sure why it doesn't complete when the response is there and ready to return...

Thanks

**Comment by VladimirRybalko** [comment]
@hfloyd seems that you get the typical async deadline.
Please try something like this:

`Task async Foo()
{
    Var result = await Client.Series.GetListByAuthorId(author.id).ConfigureAwait(false);
   // do something with result.

}`

If you call this method in sync environment. Could you try to call Wait() method after calling GetListByAuthorId.
For example: Client.Series.GetListByAuthorId(author.id).ConfigureAwait(false).Wait().

Unfortunately, I can't send you any samples because I don't have PC with Visual Studio environment now.

In any case if you still will have any questions, let us know about it.

**Comment by hfloyd** [comment]
Hi @VladimirRybalko, thanks for your assistance.

This is in a synchronous environment, so I attempted to use your second example, but get a compile error:

`'ConfiguredTaskAwaitable<IReadOnlyList<Series>>' does not contain a definition for 'Wait' and no extension method 'Wait' accepting a first argument of type 'ConfiguredTaskAwaitable<IReadOnlyList<Series>>' could be found (are you missing a using directive or an assembly reference?)	`

![image](https://user-images.githubusercontent.com/1252593/29639906-6d98d98e-882a-11e7-8da7-2a5038b538c7.png)

**Comment by VladimirRybalko** [comment]
Hi @hfloyd 
I'm really sorry for the long delay.
However I have checked your code. Seems that everything is well for me. 
May be a error depends from the specific authorId. 
Could you provide me details about your author? And I will check it again.

**Comment by VladimirRybalko** [comment]
@hfloyd 
If nothing works, could you check this way:
```c#
new TaskFactory().StartNew(() => grc.Client.Series.GetListByAuthorId(author.Id)).Unwrap().GetAwaiter().GetResult()
```

**Comment by VladimirRybalko** [comment]
I just added **ConfigureAwait(false)** to all endpoints methods.
It should be worked without any spikes.
