### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by Inrego** [adamkrogh/goodreads-dotnet#7]
Once RestSharp supports .NET Standard, I think this library should be updated to do so aswell.
Issue about the topic on RestSharp: https://github.com/restsharp/RestSharp/issues/992

**Comment by VladimirRybalko** [comment]
Hi @Inrego.
It's a good idea. I'm going to add it as soon as possible.

@adamkrogh what do you think about it?

I assume I could migrate all library code to .NET Standard 2.0 without any problems. However I have some doubts about our test project. I am not sure how new test engine will work in Travis CI. Might be you will should reconfigure some settings after migration.

**Comment by VladimirRybalko** [comment]
I've migrated solution to .NET Standard 2.0.

@adamkrogh 
Could you please reconfigure CI server to work with VS 2017 and .NET Core 2.0 XUnit tests.

**Comment by adamkrogh** [comment]
@VladimirRybalko I still can't believe all the awesome work you've been doing. I've recently changed jobs and moved to a new city so I've kind of been out of touch lately. I'll try and get everything straightened out on the CI this weekend and I'll send you a message about maybe getting the next release together soon. Thanks again!
